import { DATA_REQUIREMENTS } from "./required-fields";
import type { DataRequirementKey, ModelKey, ModelRequirement } from "./types";

const duplicateRiskWarnings = [
  "Reuse existing race, entry, horse, odds, result, feature snapshot, prediction, value calculation, and Opportunity tables.",
  "Do not create a generic predictions table or race-card workflow that bypasses Opportunity lineage.",
] as const;

function pick(keys: readonly DataRequirementKey[]) {
  return keys.map((key) => DATA_REQUIREMENTS[key]);
}

export const MODEL_REQUIREMENTS: Record<ModelKey, ModelRequirement> = {
  fundamental_win_probability_v1: {
    modelKey: "fundamental_win_probability_v1",
    label: "Fundamental win probability v1",
    purpose: "Estimate entrant win probability from pre-race racing-form fundamentals before market blending.",
    opportunityLinkageRequired: false,
    duplicateRiskWarnings,
    requirements: pick([
      "race_identity",
      "race_entries",
      "horse_identity",
      "jockey_identity",
      "trainer_identity",
      "scratches",
      "feature_snapshots",
      "model_versions",
      "prediction_outputs",
      "race_conditions",
      "horse_historical_form",
      "owner_identity",
      "jockey_performance",
      "trainer_performance",
      "workouts",
      "speed_features",
      "pace_features",
      "fractional_times",
      "final_times",
      "beaten_lengths",
      "class_movement",
      "distance_fit",
      "surface_fit",
      "track_fit",
      "pre_race_feature_snapshots",
      "official_results",
      "source_lineage",
      "ingestion_coverage",
      "holdout_evaluation",
    ]),
  },
  market_implied_probability_v1: {
    modelKey: "market_implied_probability_v1",
    label: "Market-implied probability v1",
    purpose: "Convert morning line, live odds, and pool signals into auditable market-implied probabilities.",
    opportunityLinkageRequired: false,
    duplicateRiskWarnings,
    requirements: pick([
      "race_identity",
      "race_entries",
      "horse_identity",
      "morning_line_odds",
      "live_odds_snapshots",
      "feature_snapshots",
      "model_versions",
      "prediction_outputs",
      "win_place_show_pools",
      "final_closing_odds_semantics",
      "source_lineage",
      "ingestion_coverage",
      "holdout_evaluation",
    ]),
  },
  benter_blended_probability_v1: {
    modelKey: "benter_blended_probability_v1",
    label: "Benter blended probability v1",
    purpose: "Blend fundamental probabilities with public market information under a calibrated Benter-style framework.",
    opportunityLinkageRequired: false,
    dependencies: [
      "fundamental_win_probability_v1",
      "market_implied_probability_v1",
    ],
    duplicateRiskWarnings,
    requirements: pick([
      "race_identity",
      "race_entries",
      "horse_identity",
      "feature_snapshots",
      "pre_race_feature_snapshots",
      "model_versions",
      "prediction_outputs",
      "calibrated_win_probabilities",
      "live_odds_snapshots",
      "final_closing_odds_semantics",
      "win_place_show_pools",
      "official_results",
      "source_lineage",
      "holdout_evaluation",
    ]),
  },
  value_overlay_v1: {
    modelKey: "value_overlay_v1",
    label: "Value overlay v1",
    purpose: "Convert model and market probabilities into value scores that support Opportunity scoring.",
    opportunityLinkageRequired: true,
    dependencies: ["market_implied_probability_v1"],
    duplicateRiskWarnings,
    requirements: pick([
      "race_identity",
      "race_entries",
      "horse_identity",
      "feature_snapshots",
      "pre_race_feature_snapshots",
      "model_versions",
      "prediction_outputs",
      "calibrated_win_probabilities",
      "live_odds_snapshots",
      "final_closing_odds_semantics",
      "value_calculations",
      "opportunity_score_linkage",
      "opportunity_attribution",
      "recommendation_results",
      "official_results",
      "payouts",
      "roi_performance_attribution",
      "source_lineage",
      "holdout_evaluation",
    ]),
  },
  harville_finish_order_v1: {
    modelKey: "harville_finish_order_v1",
    label: "Harville finish-order v1",
    purpose: "Use calibrated entrant win probabilities to estimate finish-order probabilities for exotic wagers.",
    opportunityLinkageRequired: true,
    dependencies: ["fundamental_win_probability_v1"],
    duplicateRiskWarnings,
    requirements: pick([
      "race_identity",
      "race_entries",
      "horse_identity",
      "scratches",
      "feature_snapshots",
      "model_versions",
      "prediction_outputs",
      "calibrated_win_probabilities",
      "finish_order_probability_support",
      "official_results",
      "result_corrections",
      "exotic_pools",
      "payouts",
      "opportunity_attribution",
      "recommendation_results",
      "roi_performance_attribution",
      "source_lineage",
      "holdout_evaluation",
    ]),
  },
};
